# Change these first
owner: joaogpiva # Your GitHub organization or username, where this repository lives
repo: upptime-hub # The name of this repository

sites:
  - name: Plataforma
    url: https://app.hub2b.com.br
  - name: Site quebrado
    url: https://thissitedoesnotexist.koj.co
  - name: Outro site quebrado
    url: https://google.com.br
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  favicon: https://app.hub2b.com.br/img/favicon.ico
  theme: light
  baseUrl: /upptime-hub
  logoUrl: https://hub2b.com.br/images/frontend/logo-primary.png
  name: Hub2b Status
  introTitle: Hub2b Status
  introMessage: Status em tempo real dos serviços da Hub2b
  navbar:
    - title: Status
      href: /upptime-hub

i18n:
  activeIncidents: Incidentes ativos
  allSystemsOperational: Todos os serviços disponíveis
  incidentReport: "Relatório do incidente #$NUMBER →"
  activeIncidentSummary: Aberto em $DATE com $POSTS atualizações
  incidentTitle: Detalhes do incidente $NUMBER
  incidentDetails: Detalhes do incidente
  incidentFixed: Resolvido
  incidentOngoing: Continua
  incidentOpenedAt: Aberto em
  incidentClosedAt: Fechado em
  incidentViewOnGitHub: Ver no GitHub
  incidentCommentSummary: Postado em $DATE por $AUTHOR
  incidentBack: ← De volta para os incidentes
  pastIncidents: Incidentes Passados
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS comentários
  liveStatus: Status Agora
  overallUptime: "Uptime geral: $UPTIME"
  overallUptimeTitle: Uptime geral
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Tempo médio de resposta
  sevelDayResponseTime: Tempo de resposta (últimos 7 dias)
  responseTimeMs: Tempo de resposta (ms)
  up: Disponível
  down: Indisponível
  degraded: Degradado
  ms: ms
  loading: Carregando
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  errorTitle: Um erro ocorreu
  errorIntro: Um erro ocorreu ao tentar recuperar o status.
  errorText: Tente novamente em alguns minutos.
  errorHome: Voltar para a tela inicial
  pastScheduledMaintenance: Histórico de manutenções
  scheduledMaintenance: Manutenção agendada
  scheduledMaintenanceSummaryStarted: Começou em $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Começa em $DATE por $DURATION minutos
  startedAt: Começou em
  startsAt: Começa em
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Completo
  incidentScheduled: Agendado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1a
  durationAll: total
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
