# Change these first
owner: joaogpiva # Your GitHub organization or username, where this repository lives
repo: upptime-hub # The name of this repository

sites:
  - name: Plataforma
    url: https://app.hub2b.com.br
  - name: Site quebrado
    url: https://thissitedoesnotexist.koj.co
  - name: Outro site quebrado
    url: https://google.com.br
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  favicon: https://app.hub2b.com.br/img/favicon.ico
  theme: light
  baseUrl: /upptime-hub
  logoUrl: https://hub2b.com.br/images/frontend/logo-primary.png
  name: Hub2b Status
  introTitle: Hub2b Status
  introMessage: Status em tempo real dos servi칞os da Hub2b
  navbar:
    - title: Status
      href: /upptime-hub

i18n:
  url: "URL"
  status: "Status"
  history: "Hist칩rico"
  up: "游릴 Operacional"
  degraded: "游릳 Degradado"
  down: "游린 Indispon칤vel"
  responseTimeGraphAlt: "Gr치fico do tempo de resposta"
  ms: "ms"
  responseTime: "Tempo de resposta"
  responseTimeDay: "Tempo de resposta (24h)"
  responseTimeWeek: "Tempo de resposta (7 dias)"
  responseTimeMonth: "Tempo de resposta (30 dias)"
  responseTimeYear: "Tempo de resposta (1 ano)"
  uptime: "Uptime total"
  uptimeDay: "Uptime (24h)"
  uptimeWeek: "Uptime (7 dias)"
  uptimeMonth: "Uptime (30 dias)"
  uptimeYear: "Uptime (1 ano)"
  liveStatus: "Status Agora"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "游릴 Todos os servi칞os operacionais"
  degradedPerformance: "游릳 Performance degradada"
  completeOutage: "游린 Indisponibilidade total"
  partialOutage: "游릲 Indisponibilidade parcial"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
